version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: 
      - zookeeper
    ports:
      - "9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9092, OUTSIDE://:9094
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2" 
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092, OUTSIDE://:9094 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_BROKER_ID: 1
#      KAFKA_CREATE_TOPICS: "demo:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
     build: ./producer-service
     depends_on:
      - kafka
     tty: true
  consumer:
     build: ./consumer-service 
     depends_on: 
      - kafka   
     tty: true

